"""add_user_profile_and_todos

Revision ID: 7684da0989e1
Revises: 0ef6d2863dfd
Create Date: 2025-12-28 18:41:40.474403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7684da0989e1'
down_revision: Union[str, Sequence[str], None] = '0ef6d2863dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_items', 'created_at')
    # ### end Alembic commands ###
