"""add invite fields

Revision ID: a1b2c3d4e5f6
Revises: 7bdeafd0caec
Create Date: 2026-01-20 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '7bdeafd0caec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('invite_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(), server_default='active', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'invite_expires_at')
    op.drop_column('users', 'invite_token')
    # ### end Alembic commands ###
